on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '18', '20']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn build

      - name: Run unit tests
        run: yarn test
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true 
          directory: ./coverage
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }} 
          verbose: true

  publish:
    name: Publish @leapfrogtechnology/async-store package
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RIBBY_GITHUB_TOKEN }}

      - name: Set git user
        run: |
          git config user.name "Ribby"
          git config user.email "bot@lftechnology.com"

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install gems
        run: |
          gem install github_changelog_generator

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn

      - name: Install hub
        run: |
          sudo apt update
          sudo apt install hub
          hub --version

      - name: Run release script
        env:
          GITHUB_TOKEN: ${{ secrets.RIBBY_GITHUB_TOKEN }}
        run: ./release.sh compare_and_release

      - name: Deploy to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn publish
